spring:
  application:
    name: PBL5
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres.jnabzysmdvaraqxrvwup
    password: MinhchieN0905

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: MyVerySecureJWTSecretKeyThatIsAtLeast32BytesLongForHMACSHA256Algorithm2024
  access-token-expiration: 1000 # 1 giay
  refresh-token-expiration: 604800000 # 7 ngay

app:
  security:
    refresh-cookie-secure: false

google:
  client:
    id: 286951222811-de805r44tl8ut7mck43tlqao2spjlj18.apps.googleusercontent.com
