spring:
  application:
    name: PBL5
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?reWriteBatchedInserts=true
    driverClassName: org.postgresql.Driver
    username: postgres.jnabzysmdvaraqxrvwup
    password: MinhchieN0905
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

  mail:
    host: smtp.gmail.com
    port: 587
    username: megamart.noreply@gmail.com
    password: "hkeelvyesaxtobyw"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: MyVerySecureJWTSecretKeyThatIsAtLeast32BytesLongForHMACSHA256Algorithm2024
  access-token-expiration: 7200000 # 1 gio
  refresh-token-expiration: 604800000 # 7 ngay

app:
  security:
    refresh-cookie-secure: false

google:
  client:
    id: 286951222811-de805r44tl8ut7mck43tlqao2spjlj18.apps.googleusercontent.com

vnpay:
  tmnCode: "6OA3DYF3"
  hashSecret: "358D3BILHTPN4C0JUXFNF5046YEGTM0X"
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl: "http://localhost:8080/api/public/payment/vnpay-return"

momo:
  partnerCode: "MOMO"
  accessKey: "MOMO"
  secretKey: "MOMO"
  url: "https://test-payment.momo.vn/v2/gateway/api/create"
  redirectUrl: "http://localhost:8080/api/public/payment/momo-return"
  ipnUrl: "http://localhost:8080/api/public/payment/momo-ipn"

cloudinary:
  cloud-name: dtyqksfic
  api-key: "572615717297474"
  api-secret: "rqy__CPlTP8PLRc8AYz-NoNRDr4"


